# Generated by Django 4.1.7 on 2023-03-26 12:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_question_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_original', models.BooleanField(default=True)),
                ('order', models.CharField(db_index=True, max_length=256)),
                ('type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice')], default='SINGLE_CHOICE', max_length=20)),
                ('original_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_in_tests', to='questions.question')),
                ('question_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionpool')),
            ],
            options={
                'unique_together': {('question_pool', 'question'), ('question_pool', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_correct', models.BooleanField()),
                ('order', models.CharField(db_index=True, max_length=256)),
                ('original_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies_in_tests', to='questions.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
            options={
                'unique_together': {('question', 'answer'), ('question', 'order')},
            },
        ),
    ]
