# Generated by Django 4.1.7 on 2023-05-29 12:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_correct', models.BooleanField()),
                ('order', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_original', models.BooleanField(default=True)),
                ('order', models.IntegerField(db_index=True)),
                ('type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice')], default='SINGLE_CHOICE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
