# Generated by Django 4.1.7 on 2023-05-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionpool',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='questionpool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_pools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='questionpool',
            constraint=models.UniqueConstraint(models.F('user'), models.F('name'), name='unique_question_pool_name_for_user', violation_error_message='You have already created a question pool with this name'),
        ),
    ]
