# Generated by Django 4.1.7 on 2023-05-29 17:41

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_unique_together_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='question',
            name='update_answers_order_on_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='question',
            name='update_answers_order_on_delete',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_answers_order_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                IF NOT pg_trigger_depth() > 1 THEN\n                    IF NEW."order" > OLD."order" THEN\n                        UPDATE questions_question\n                        SET "order" = "order" - 1\n                        WHERE "order" > OLD."order" AND "order" <= NEW."order" AND question_pool_id = OLD.question_pool_id;\n                    ELSEIF NEW."order" < OLD."order" THEN\n                        UPDATE questions_question\n                        SET "order" = "order" + 1\n                        WHERE "order" >= NEW."order" AND "order" < OLD."order";\n                    END IF;\n                END IF;\n                RETURN NEW;\n                ', hash='e9c12bfe2a1dff7fc9de65acfc8646c12bb9c478', operation='UPDATE', pgid='pgtrigger_update_answers_order_on_update_b1451', table='questions_question', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_answers_order_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                IF NOT pg_trigger_depth() > 1 THEN\n                    UPDATE questions_question\n                    SET "order" = "order" - 1\n                    WHERE "order" > OLD."order" AND question_pool_id = OLD.question_pool_id;\n                END IF;\n                RETURN OLD;\n                ', hash='b57590ee4f11469deb1f9efbfa3ce2989b604379', operation='DELETE', pgid='pgtrigger_update_answers_order_on_delete_66a6c', table='questions_question', when='BEFORE')),
        ),
    ]
