# Generated by Django 4.1.7 on 2023-05-30 18:04

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_options'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='question',
            trigger=pgtrigger.compiler.Trigger(name='update_answers_order_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                IF NOT pg_trigger_depth() > 1 THEN\n                    UPDATE questions_question\n                    SET "order" = "order" + 1\n                    WHERE "order" >= NEW."order" AND question_pool_id = NEW.question_pool_id;\n                END IF;\n                RETURN NEW;\n                ', hash='6ae3f00da71330c49385bcfd2cfd6cca3445bda4', operation='INSERT', pgid='pgtrigger_update_answers_order_on_insert_50d59', table='questions_question', when='BEFORE')),
        ),
    ]
