# Generated by Django 4.1.7 on 2023-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_answer_options_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
