# Generated by Django 4.1.7 on 2023-04-06 11:21

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('max_question_pools', models.PositiveIntegerField()),
                ('max_questions_total', models.PositiveIntegerField()),
                ('max_questions_in_a_test', models.PositiveIntegerField()),
                ('max_tests', models.PositiveIntegerField()),
                ('max_groups', models.PositiveIntegerField()),
                ('max_users_in_a_group', models.PositiveIntegerField()),
                ('max_answers_to_a_question', models.PositiveIntegerField()),
                ('can_see_logs', models.BooleanField()),
                ('can_see_statistics', models.BooleanField()),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
