# Generated by Django 4.1.7 on 2023-04-06 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='testquestion',
            unique_together={('test', 'question'), ('test', 'order')},
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(models.F('user'), models.F('name'), name='unique_test_name', violation_error_message='You have already created test with this name'),
        ),
    ]
