# Generated by Django 4.1.7 on 2023-06-03 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_question_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_of_questions',
        ),
    ]
