# Generated by Django 4.1.7 on 2023-06-03 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('tests', '0004_remove_test_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='group',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
