# Generated by Django 4.1.7 on 2023-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_attempt_group_alter_attempt_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attemptanswer',
            name='is_marked',
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
