# Generated by Django 4.1.7 on 2023-06-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_update_answers_order_on_delete_and_more'),
        ('tests', '0009_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('ENTERED_QUESTION', 'Entered question'), ('SELECTED_ANSWER', 'Selected answer'), ('DESELECTED_ANSWER', 'Deselected answer'), ('MARKED_AS_ANSWERED', 'Marked as answered')], default='ENTERED_QUESTION', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer'),
        ),
        migrations.AddField(
            model_name='log',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
            preserve_default=False,
        ),
    ]
