# Generated by Django 4.1.7 on 2023-06-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_log_action_log_answer_log_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
