# Generated by Django 4.1.7 on 2023-06-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_update_answers_order_on_delete_and_more'),
        ('tests', '0011_remove_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
