# Generated by Django 4.1.7 on 2023-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_log_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('ENTERED_QUESTION', 'Entered question'), ('SELECTED_ANSWER', 'Selected answer'), ('DESELECTED_ANSWER', 'Deselected answer'), ('MARKED_AS_ANSWERED', 'Marked as answered'), ('UNMARKED_AS_ANSWERED', 'Unmarked as answered')], max_length=20),
        ),
    ]
